# Generated by Django 6.0.3 on 2026-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times', '3 Times Daily'), ('as_needed', 'As Needed')], max_length=50, null=True),
        ),
    ]
