# Generated by Django 6.0.3 on 2026-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=20),
        ),
    ]
