# Generated by Django 6.0.3 on 2026-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
