# Generated by Django 6.0.3 on 2026-05-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='users.payment'),
        ),
    ]
