# Generated by Django 6.0.3 on 2026-05-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_start_time', models.TimeField(default='08:00')),
                ('clinic_end_time', models.TimeField(default='17:00')),
                ('appointment_buffer', models.IntegerField(default=15)),
                ('new_appointment_alerts', models.BooleanField(default=True)),
                ('emergency_alerts', models.BooleanField(default=True)),
                ('lab_result_alerts', models.BooleanField(default=False)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
            ],
        ),
    ]
