# Generated by Django 6.0.3 on 2026-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
