# Generated by Django 6.0.3 on 2026-05-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctor_bio_doctor_image_alter_doctor_clinic_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sharing', models.BooleanField(default=False)),
                ('profile_visibility', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('language', models.CharField(default='english', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
