# Generated by Django 6.0.3 on 2026-05-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_clinic_latitude_alter_clinic_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('payment', 'Payment'), ('prescription', 'Prescription'), ('lab', 'Lab'), ('emergency', 'Emergency'), ('entry', 'Clinic Entry')], max_length=20),
        ),
    ]
