# Generated by Django 6.0.3 on 2026-05-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_notification_options_alter_notification_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='ai_diagnosis',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='ai_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='users.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='users.appointment'),
        ),
    ]
