# Generated by Django 6.0.3 on 2026-05-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_aianalysis_ai_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_insights', to='users.appointment')),
            ],
        ),
    ]
