# Generated by Django 6.0.3 on 2026-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_clinicalinsight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='temperature',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(),
        ),
    ]
