# Generated by Django 6.0.3 on 2026-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_medicalrecord_heart_rate_medicalrecord_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
