# Generated by Django 6.0.3 on 2026-06-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notification_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='payload',
        ),
    ]
